### ISSUE TITLE
CORS not working on error pages

### ISSUE THREAD

**Issue by ghost** [nordsoftware/lumen-cors#1]
Hi there, 

I tried using your package, but I still get the error that my origin is not allowed.

This is my config: 

```
 <?php

 return [

'allowOrigins'     => ['*'],

'allowHeaders'     => ['*'],

'allowMethods'     => ['*'],

'allowCredentials' => false,

'exposeHeaders'    => [],

'maxAge'           => 3600,

];
```

Am I doing something wrong?

**Comment by ghost** [comment]
It seems like if Lumen returns a 500 error the header does not get set. Am I the only one encountering this issue?

**Comment by cniska** [comment]
If an exception is thrown before the middleware is ran the headers cannot be set. 

Please reopen this issue if fixing the issue causing the 500 does not solve this issue.
