### ISSUE TITLE
Use empty instead of not

### ISSUE THREAD

**Issue by cniska** [nordsoftware/lumen-cors#14]
see https://scrutinizer-ci.com/g/nordsoftware/lumen-cors/issues/develop/files/src/CorsService.php?orderField=path&order=asc&fileId=src%2FCorsMiddleware.php&honorSelectedPaths=0#inspectioncomment-13939821

**Comment by Jalle19** [comment]
It's not that simple, allowHeaders will be set to true if \* is configured for example.

**Comment by cniska** [comment]
Yeah I know, this requires some refactoring. I still think we should fix this.

**Comment by Jalle19** [comment]
Definitely
