### ISSUE TITLE
Cannot redeclare class Cors

### ISSUE THREAD

**Issue by li0nel** [nordsoftware/lumen-cors#2]
In CorsServiceProvider.php
on line 21: class_alias('Nord\Lumen\Cors\CorsFacade', 'Cors');

During PHPUnit tests, this line is called twice and fails on redeclaring class Cors

Any idea?

Thx

**Comment by cniska** [comment]
You must have a class called `Cors` in the root namespace. That's the only reason I can think of that could cause that error.

**Comment by catalinux** [comment]
The problem is that the application is loaded again to instantiate the Application object. I made some changes: https://github.com/nordsoftware/lumen-cors/commit/9e4f966695fcc18523174632ca21ecc9d762c49d

**Comment by boedy** [comment]
temp fix until pull request get's accepted:

``` php
if( ! class_exists('Cors')){
    $app->register('Nord\Lumen\Cors\CorsServiceProvider');
}
```

**Comment by cniska** [comment]
That's true, but the proper fix is to wrap registering of the `Cors` alias with a `class_exists('Cors')` check.

**Comment by catalinux** [comment]
@crisu83 do you want me to change my pull request https://github.com/nordsoftware/lumen-cors/commit/9e4f966695fcc18523174632ca21ecc9d762c49d ?

**Comment by cniska** [comment]
@catalinux Sure.

**Comment by cniska** [comment]
I just merged a fix for this.
