### ISSUE TITLE
Access-Control-Request-Headers in firefox

### ISSUE THREAD

**Issue by jake142** [nordsoftware/lumen-cors#31]
I noticed angular running in firefox sends Access-Control-Request-Headers as comma separated string without spaces. This cause this to fail:

            $headers = $request->headers->get('Access-Control-Request-Headers');

            if (is_string($headers)) {
                foreach (explode(', ', $headers) as $header) {

I added a simple middleware to deal with it, but it would be great to have it in package. Eg. support both explode(', '.. and explode(','..

**Comment by soderluk** [comment]
Hi @jake142,

you can always create a pull request, and we'll go through it and merge. Check the [guidelines](https://github.com/nordsoftware/lumen-cors/blob/develop/.github/CONTRIBUTING.md) for contributing.

**Comment by Jalle19** [comment]
I think it would be best to explode on `,` and then use `trim()` later on.

**Comment by Jalle19** [comment]
This could potentially be the root cause for https://github.com/nordsoftware/lumen-cors/issues/21 too
