### ISSUE TITLE
Same host request are blocked

### ISSUE THREAD

**Issue by yonguelink** [nordsoftware/lumen-cors#50]
### What did you do?

* Allow one website for CORS request (so not `*`)
* Make a request on the same origin

### What did you expect to happen?

* The request made on the same origin should've succeeded

### What actually happened?

* The request got an 403 Unauthorized from the CORS

### What versions of PHP, Lumen and this module are you using?

PHP 5.6
Lumen 5.4
This lib 2.2

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

I don't really have an example at hand, but it should be pretty simple if you have any api/app/whatever already bundled with Lumen and using this lib.

In the config file, specify anything else than your host server url & `*`

Then make a request to your host.

Example config file:
Note I omitted the details that came from your own example config file in this repo.

```php
...
// Lets say your server host is "https://example.com"
// And you offer an endpoint for "https://website.com"
'allow_origins' => ['https://website.com'],
...
```

Now you just have to create a webpage on `https://example.com` and query your host. It'll fail.

It'd be necessary to check if the current request has been made on the same origin before failing on CORS.

**Comment by Jalle19** [comment]
I don't see what the problem is here? If you only allow `https://website.com` then obviously requests to `https://example.com` will fail the CORS check.

**Comment by Jalle19** [comment]
Please re-open this if you still consider it an issue
