### ISSUE TITLE
It's not working!

### ISSUE THREAD

**Issue by omidamraei** [nordsoftware/lumen-cors#51]
I completely follow the installation instruction but it's not working. Still getting this error:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.domain.dev/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

I'm using PHP 7.0, Lumen 5.5 and  LumenCors 2.2

**Comment by cniska** [comment]
@amraei did you find the issue?

**Comment by omidamraei** [comment]
@crisu83 Yes, it wasn't related to your package. There was an error in my code.
