### ISSUE TITLE
Bump minimum PHP version to 7.1

### ISSUE THREAD

**Issue by Jalle19** [nordsoftware/lumen-cors#55]
We're gonna have to bump the major version anyway so might as well go all in

**Comment by hugovk** [comment]
PHP 7.0 is fully EOL soon, on 3 Dec 2018.

![image](https://user-images.githubusercontent.com/1324225/46669113-268d4600-cbd7-11e8-819d-5de1fb9e144c.png)


https://secure.php.net/supported-versions.php

**Comment by Jalle19** [comment]
Yep
