### ISSUE TITLE
Getting error Type error: Argument 1 passed to Nord\Lumen\Cors\CorsService::__construct() must be of the type array, null given, called in D:\laragon\www\Kannexa\users_api\vendor\nordsoftware\lumen-cors\src\CorsServiceProvider.php on line 33

### ISSUE THREAD

**Issue by ramsaiphp** [nordsoftware/lumen-cors#62]
### What versions of PHP, Lumen and this module are you using?

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```php
code goes here
```

**Comment by ramsaiphp** [comment]
I have frontend which is laravel and i have backend which is lumen. I am calling lumen api from laravel i am getting cors issue. So i google and install your package as mentioned. Finally i am getting below error:

Type error: Argument 1 passed to Nord\Lumen\Cors\CorsService::__construct() must be of the type array, null given, called in D:\laragon\www\Kannexa\users_api\vendor\nordsoftware\lumen-cors\src\CorsServiceProvider.php on line 33

**Comment by Jalle19** [comment]
Sounds like you're missing the config/cors.php file?

**Comment by ramsaiphp** [comment]
Yes i did it. Now getting different error
Thanks

**Comment by Jalle19** [comment]
Okay, please open a new issue if you have problems with the new error
