### ISSUE TITLE
Feature Request - Allow origins accept patters too

### ISSUE THREAD

**Issue by ngabor84** [nordsoftware/lumen-cors#67]
Hi,

It would be useful if in the config file the allow_origins option also accept patterns, not just exact domains.
For example you have have domains like test1.example.com ... test279.example.com and you able to set it like ['*.example.com'], and don't have to list all your domains.

Thanks,
Gabor

**Comment by Jalle19** [comment]
This has been requested before but the effort never amounted to anything. Perhaps it would make sense to simply override the method that checks if an origin is allowed, then you could do anything you want?
