### ISSUE TITLE
Fatal error: Class 'Nord\Lumen\Cors\CorsServiceProvider' not found 

### ISSUE THREAD

**Issue by razor9999** [nordsoftware/lumen-cors#7]
Fatal error: Class 'Nord\Lumen\Cors\CorsServiceProvider' not found

**Comment by cniska** [comment]
Could you be a bit more specific on how you encountered this error?

**Comment by soderluk** [comment]
Is this related to running tests? If it is, then you need to add in _bootstrap.php

``` php
require __DIR__ . '/../vendor/autoload.php';
```

**Comment by hugovk** [comment]
If the problem still persists, please add more information and we can reopen this.
