### ISSUE TITLE
Support for Illuminate/support 6.*

### ISSUE THREAD

**Issue by webwisejordan** [nordsoftware/lumen-cors#72]
When trying to use this with Lumen 6.2 this fails to install via composer due to a dependency on Illuminate/support 5.4.  The newest version is 6.7 and other packages used with Lumen seem to be starting to require ^6.0, which causes a dependency conflict with lumen-cors.

Not sure if there would be breaking changes in making the version jump, but if not, is it possible to update to support 6.* as well?

**Comment by Jalle19** [comment]
This is being worked on here: https://github.com/digiaonline/lumen-cors/pull/71

**Comment by webwisejordan** [comment]
Oh, sorry about that - didn't see that one.  Thank you for all of your effort.

**Comment by Jalle19** [comment]
https://packagist.org/packages/nordsoftware/lumen-cors#3.2.0
