### ISSUE TITLE
Installed and configured as defined but I still cant do a request from a different host

### ISSUE THREAD

**Issue by philmetzger** [nordsoftware/lumen-cors#76]
### What did you do?
I did as you say in your readme: https://github.com/digiaonline/lumen-cors to install and configure lumen-cors

### What did you expect to happen?
That my error message would disappear and I could do requests. Error message:
`Access to fetch at 'http://localhost:8000/feedback/add' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

### What actually happened?
nothing

### What versions of PHP, Lumen and this module are you using?
PHP: 7.3.3
Lumen: "laravel/lumen-framework": "5.8.*",
Lumen-cors: "nordsoftware/lumen-cors": "^3.2",

Here is my app.php:
```php
$app->configure('cors');

$app->middleware([
    'Nord\Lumen\Cors\CorsMiddleware',
]);

$app->register('Nord\Lumen\Cors\CorsServiceProvider');
```

Any idea why I still get cors issues?
How do I know if this is actually running in the middleware?

**Comment by Jalle19** [comment]
Did you add config/cors.php too?

**Comment by philmetzger** [comment]
Yep it looks like this:
```
<?php
return [
    'allow_origins' => ['*'],
    'allow_headers' => ['*'],
    'allow_methods' => ['*'],
    'allow_credentials' => false,
    'expose_headers' => [],
    'max_age' => 0,
];

```

**Comment by philmetzger** [comment]
Also it seems when I go directly to: `http://localhost:8000/feedback/add` in my browser, then It seems to work fine.

**Comment by Jalle19** [comment]
Try removing `$app->configure('cors');` from bootstrap/app.php

**Comment by philmetzger** [comment]
Removing that doesnt help. Still get the cors issue :(

I tried also adding a die(); in my public/index.php file and thought then the request should die before the cors issue right? But it doesnt die.

**Comment by philmetzger** [comment]
AH i found the issue. My endpoint was not returning anything so I added `return response([]);`

Not sure why that would cause the cors issue though.
