### ISSUE TITLE
Not working on Lumen 6.3.5

### ISSUE THREAD

**Issue by poppabear8883** [nordsoftware/lumen-cors#77]
### What did you do?
`Upgraded to Lumen ^6.0`

### What did you expect to happen?
`Everything still works`

### What actually happened?
`It simply stopped working`

### What versions of PHP, Lumen and this module are you using?
`PHP 7.2`
`Lumen 6.3.5`
`lumen-cors 3.2.0`

I have done everything stated in the readme. I have verified that this is working on `Lumen 5.8` but NOT on `Lumen 6.3.5`

I have no idea why.

**Comment by Jalle19** [comment]
Hard to tell without more information. You can add a `die("foo")` statement to the middleware to see if it's being run at all. If you have a debugger you can just set a breakpoint instead.

**Comment by poppabear8883** [comment]
Can you not reproduce the issue that i describe above ? It seems that i'm doing everything on my end correctly if it appears to work on Lumen 5.8 but not Lumen 6.3.5 ?

If you can not reproduce the issue, I have no problems digging deeper into my setup and trying to figure out why my setup is different than yours.

**Comment by hugovk** [comment]
For what it's worth, I just triggered a new CI build, and that passed with Lumen 6.3.5:

* https://travis-ci.org/github/digiaonline/lumen-cors/jobs/666313236#L353

The previous build was with 6.2.0 and passed:

* https://travis-ci.org/github/digiaonline/lumen-cors/jobs/626661470#L332

(I've turned on a monthly cron for the CI to help catch any failures from new releases.)

**Comment by poppabear8883** [comment]
@hugovk Thanks for that. We at least know that the tests are passing and looks like code coverage is good on the methods.

I can try and figure out what the deal is with my particular setup then and will report back of anything that is note worthy.

**Comment by Jalle19** [comment]
@poppabear8883 is this still an issue?

**Comment by poppabear8883** [comment]
This appears to have been an issue on my end. I'll close this issue.
